### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMaize#61]
CI needs to be brought up to the same standards as the other CMakePP repos. Specifically actions for:

- [ ] building documentation (verifying it works)
- [ ] deploying documentation
- [ ] running unit tests
- [ ] applying licenses to files
- [ ] semantic versioning

**Comment by zachcran** [comment]
I believe this is the current status of this issue's completion (I'm not sure why I can't tie issues to the specific tasks):

- [x] building documentation (verifying it works) (completed via #64)
- [x] deploying documentation (completed via #64)
- [x] running unit tests (completed via #74)
- [ ] applying licenses to files
- [ ] semantic versioning
